### ISSUE TITLE
Axios default maxBodyLength = 10MB, no way to override

### ISSUE THREAD

**Issue by trevyn** [yakovkhalinsky/backblaze-b2#45] opened 2018-06-28 00:06 UTC
Looks like the switch to Axios has also limited upload parts to 10MB, since there's no way to access the underlying Axios object to set a larger maxBodyLength.

**Comment by jamiesyme** [comment] 2018-07-06 02:55
It looks like the issue was half-fixed with [this](https://github.com/axios/axios/pull/1287) PR, which is merged in axios@0.18.0. This allows us to specify a `maxContentLength` option to axios, and as long as it's large enough, everything is a-okay. In my tests, I just passed the file part size as the `maxContentLength` and that seemed to work.

However, it's only "half-fixed" because you need to explicitly pass `maxContentLength` to axios, otherwise it will allow the internal `follow-redirects` package to use the default 10MB. I found [this](https://github.com/axios/axios/issues/1362) issue which seems to identify the problem, but there hasn't been much activity on it lately.

Perhaps using the file part size as the `maxContentLength` is a reasonable workaround for now?

**Comment by roccomuso** [comment] 2018-07-06 11:00
I can confirm that with axios@0.18.0 it works.

**Comment by damianobarbati** [comment] 2018-10-05 15:20
I currently worked this around with `maxContentLength: Infinity`, anyway:
- shouldn't axios fill `maxContentLength` with actual formData object size? (I'm uploading multipart files)
- shouldn't axios throw error instead of returning an empty/undefined response?

**Comment by pkyt** [comment] 2019-01-11 09:37
One way to configure maxBodyLength in axios

**Comment by Amit-A** [comment] 2019-02-20 03:00
#62 should fix this - allows access to the underlying axios object

**Comment by Amit-A** [comment] 2019-02-26 03:10
#62 merged, fixed.

**Closed by Amit-A** 2019-02-26 03:10 UTC
Labels: bug, downstream

**Comment by LunarFuror** [comment] 2019-06-07 16:33
I can confirm here that for those of you using putFileContents having an issue here,
await client.putFileContents( globals.GLOBAL_NEXTCLOUD_FOLDER + fileName, file.buffer, {
            overwrite: false,
            maxContentLength: 1024 ** 3
        });
