### ISSUE TITLE
download binary

### ISSUE THREAD

**Issue by GoNode5** [yakovkhalinsky/backblaze-b2#15] opened 2016-03-11 17:13 UTC
cant get a valid file (test zip and mp3)
```javascript
   b2.downloadFileById(fileid).then(function(file){
			// tried   var bitmap = new Buffer(file.data,'base64');
    			//fs.writeFile('testload.txt',bitmap)
			
         		   fs.writeFile('testload.mp3',file.data, function(err) {
						console.log(err);
				});
});
```
Any idea? thnx

**Comment by yakovkhalinsky** [comment] 2016-03-11 23:09
Try tried adding an error function to the `then()` and let me know what error is being returned like this:
```
b2.downloadFileById(fileid).then(
   function(file){
      fs.writeFile('testload.mp3',file.data, function(err) {
         console.log(err);
       });
   },
   function(err) {
      console.log('err from b2', err);
   }
);
```

**Comment by GoNode5** [comment] 2016-03-14 09:53
thnx there is no error (1 bucket with 1 file)
- the file is downloaded but double in size
- when I do list.files[1].fileId (invalid non excist file) no error

```
b2.listFileNames({bucketId: data.buckets[0].bucketId}).then( 							             	
		function(list)	 {									
			b2.downloadFileById(list.files[0].fileId).then(
				function(file){				
					  fs.writeFile('testload.mp3',file.data, function(err) {
						 console.log(err);
					   });
			   },
			   function(err) {
				  console.log('err from download b2', err);
			   }
			);
		},
		function(err) {
		 console.log('err from b2', err);
		} 
	)

**Comment by yakovkhalinsky** [comment] 2016-03-15 09:13
Have reproduced the issue you're having.

Not sure what has changed. I will investigate and make a fix soon. :+1:

**Comment by yakovkhalinsky** [comment] 2016-03-16 08:42
@GoNode5 managed to track down the issue.

Seems that for binary data the `request` module assumes String data. Good news is the fix will be in shortly :+1:

**Comment by yakovkhalinsky** [comment] 2016-03-16 08:43
Ah as it turns out I do this in the by filename function but no in the by id function.

:facepalm:

**Comment by yakovkhalinsky** [comment] 2016-03-16 08:50
Going to bump the version and publish to npm in the next few minutes :dart:

**Closed by yakovkhalinsky** 2016-03-16 08:50 UTC
Labels: bug, question

**Comment by yakovkhalinsky** [comment] 2016-03-16 09:04
@GoNode5 v0.9.11 now on npm, thanks for the report and patience :+1:

**Comment by GoNode5** [comment] 2016-03-16 11:04
no problem at all, its now working :-) thnx

**Comment by haywirez** [comment] 2018-05-12 14:27
Important: need to add `'arraybuffer'` as a `responseType` property to make this work as it should. ```

b2.downloadFileById({
    fileId: fileId,
    responseType: 'arraybuffer',
    ...
})
```
