### ISSUE TITLE
delete issue?

### ISSUE THREAD

**Issue by mmccallum** [yakovkhalinsky/backblaze-b2#9] opened 2016-01-15 05:03 UTC
I store files using "folders".  So as an example, my structure looks like this:

<BUCKET>{folder}/{folder}/{file.ext}

When using deletefileversion, I get back the following:
{ code: 'file_not_present',
  message: 'file not present: -K82QoL4BCVSRqv3u3r4%2Fcollages%2Fd3f81d06-973d-4478-d19e-0677d8bdc681.jpg 4_zd55dcf6fe56cedf45d130010_f11275d83e9982f7a_d20160115_m035841_c001_v0001012_t0043',
  status: 400 }

The actual filename is:
-K82QoL4BCVSRqv3u3r4/collages/d3f81d06-973d-4478-d19e-0677d8bdc681.jpg 

So, it appears that the filename is being urlencoded when perhaps it should not be? Or perhaps something else is broken.

Thanks!
-Matt

**Comment by yakovkhalinsky** [comment] 2016-01-15 22:18
thanks for the report @mmccallum I'll have a look at the docs and check this.

I have a feeling that the API says to URL encode the name, but I'll double check this.

**Comment by yakovkhalinsky** [comment] 2016-01-15 22:18
For the upload file API is says:
```
The name of the file, in percent-encoded UTF-8. For example, spaces should be replaced with %20. For more information, see Files for requirements on file names and String Encoding for how to encode strings.
```

I'll have a look through how I do this and do a quick test with your example and get to you :+1:

**Comment by yakovkhalinsky** [comment] 2016-01-15 22:27
Ok I have reproduced the error. I'll look at fixing it now :dart:

**Comment by yakovkhalinsky** [comment] 2016-01-15 22:31
Ok the trouble seems to be that I need to URL encode everything except the `/` in the filename.

Patch coming shortly :+1:

**Comment by yakovkhalinsky** [comment] 2016-01-16 00:25
Fix merged, will publish to npm shortly :+1:

**Closed by yakovkhalinsky** 2016-01-16 00:25 UTC
Labels: bug

**Comment by mmccallum** [comment] 2016-01-16 00:28
Thanks!  Won't get a chance to test until next week. Will report if there
are any issues.

Matt

**Comment by yakovkhalinsky** [comment] 2016-01-16 00:29
No worries :+1:  help to highlight the same problem with the other file functions :dancers:
